const tripData = [
	{
		id: 1,
		title: 'Vietnam',
		date: 'November 2018',
		imgName: 'vietnamSunrise_opt.jpg',
		photoUrls: ['glassBeach.jpg', 'lostCoast.jpg', 'glassBeach.jpg'],
		textFile: 'vietnam2018.md',
		summaryText: 'Hiked around Sapa and sunbathed in Halong Bay',
		expenseImage: null,
		videoId: 'FsRQeaqDrw4',
		enableComments: true
	},
	{
		id: 2,
		title: 'Hawaii',
		date: 'May 2019',
		imgName: 'HawaiianMilkyway_opt.jpg',
		photoUrls: ['hawaiianMilkyway.jpg', 'nz2.jpg', 'glassBeach.jpg'],
		textFile: 'hawaii2019.md',
		summaryText: 'Camped under the Milky Way listening to the waves',
		expenseImage: null,
		videoId: 'fFLoXtVG5bM',
		enableComments: true
	},
	{
		id: 3,
		title: 'Glacier National Park',
		date: 'July 2019',
		imgName: 'glacier_opt.jpg',
		photoUrls: ['glacier.jpg', 'lostCoast.jpg', 'glassBeach.jpg'],
		textFile: 'glacier2019.md',
		summaryText: 'Set out to find the coolest alpine lakes',
		expenseImage: null,
		videoId: null,
		enableComments: true
	},
		{
		id: 4,
		title: 'Alaska',
		date: 'July 2018',
		imgName: 'DenaliBackpacking.jpg',
		photoUrls: ['glassBeach.jpg', 'DenaliBackpacking.jpg', 'glassBeach.jpg'],
		textFile: 'alaska2018.md',
		summaryText: 'Bushwacked for miles through Denali National Park',
		expenseImage: null,
		videoId: null,
		enableComments: true
	},
	{
		id: 5,
		title: 'Laos',
		date: 'November 2018',
		imgName: 'waterfall.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'laos2018.md',
		summaryText: 'Explored the many waterfalls, rivers and cave systems',
		expenseImage: null,
		videoId: 'XEvDEIsByWw',
		enableComments: true
	},
	{
		id: 6,
		title: 'Philippines',
		date: 'May 2016',
		imgName: 'puertoPrincesa_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'philippines2016.md',
		summaryText: 'Slurped up mango shakes every day',
		expenseImage: null,
		videoId: 'QsDiXvC_WEA',
		enableComments: true
	},
	{
		id: 7,
		title: 'Baja California, Mexico',
		date: 'October 1, 2019 - October 7, 2019',
		imgName: 'bajaCalifornia_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'bajaCaliforniaMexico.md',
		summaryText: 'Relaxed on beautiful beaches and devoured delicious tacos',
		expenseImage: 'mexicoX_opt.png',
		videoId: 'T_ziz7DzG2A',
		enableComments: true
	},
	{
		id: 8,
		title: 'Mexico City, Mexico',
		date: 'October 8, 2019 - October 14, 2019',
		imgName: 'teotihuacan_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'mexicoCity.md',
		summaryText: 'Walked through  museums, cathedrals, and even ancient pyramids',
		expenseImage: 'mexicoX_opt.png',
		videoId: 'T_ziz7DzG2A',
		enableComments: true
	},
	{
		id: 9,
		title: 'Oaxaca, Mexico',
		date: 'October 15, 2019 - October 23, 2019',
		imgName: 'oaxacaSunset_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'oaxacaMexico.md',
		summaryText: 'Ate our way around this beautiful, mountainous region',
		expenseImage: 'mexicoX_opt.png',
		videoId: 'T_ziz7DzG2A',
		enableComments: true
	},
	{
		id: 10,
		title: 'Cuba',
		date: 'November 6, 2019 - November 12, 2019',
		imgName: 'cuba_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'cuba.md',
		summaryText: 'Toured cobblestone streets, lush tobacco farms, and 1950s automobiles',
		expenseImage: null,
		videoId: null,
		enableComments: true
	},
	{
		id: 11,
		title: 'Yucatan, Mexico',
		date: 'October 23, 2019 - November 16, 2019',
		imgName: 'chichenItza_us_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'yucatan.md',
		summaryText: 'Splashed into a number of lagoons, cenotes, and oceans',
		expenseImage: 'mexicoX_opt.png',
		videoId: 'T_ziz7DzG2A',
		enableComments: true
	},
	{
		id: 12,
		title: 'Belize',
		date: 'November 16, 2019 - November 24, 2019',
		imgName: 'belizeTurtle_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'belize.md',
		summaryText: 'Snorkeled alongside turtles, sharks, and manatees',
		expenseImage: 'belizeX_opt.png',
		videoId: 'ZN8QzMAgQcc',
		enableComments: true
	},
	{
		id: 13,
		title: 'Guatemala',
		date: 'November 24, 2019 - December 9, 2019',
		imgName: 'guatemala_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'guatemala.md',
		summaryText: 'Fulfilled our adventurous nature with caves, rivers, lakes and erupting volcanos',
		expenseImage: 'guatemalaX_opt.png',
		videoId: 'ZN8QzMAgQcc',
		enableComments: true
	},
	{
		id: 14,
		title: 'El Salvador',
		date: 'December 9, 2019 - December 12, 2019',
		imgName: 'salvador_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'elSalvador.md',
		summaryText: 'Surfed the Pacific waves and stuffed our faces with pupusas',
		expenseImage: 'elSalvadorX_opt.png',
		videoId: 'IlSz6vEHd58',
		enableComments: true
	},
	{
		id: 15,
		title: 'Nicaragua',
		date: 'December 13, 2019 - January 3, 2020',
		imgName: 'nica_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'nicaragua.md',
		summaryText: 'Enjoyed the land of coffee, treehouses, and canyons',
		expenseImage: 'nicaraguaX_opt.png',
		videoId: 'IlSz6vEHd58',
		enableComments: true
	},
	{
		id: 16,
		title: 'Costa Rica',
		date: 'January 3, 2019 - January 11, 2020',
		imgName: 'costarica_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'costarica.md',
		summaryText: 'Meandered through mystic cloud forests, rain forests, and dry forests',
		expenseImage: 'costaRicaX_opt.png',
		videoId: 'upJmacEjONk',
		enableComments: true
	},
	{
		id: 17,
		title: 'Panama',
		date: 'January 11, 2020 - January 24, 2020',
		imgName: 'panama_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'panama.md',
		summaryText: 'Experienced the contrast of the big city and the tiny island villages of Panama',
		expenseImage: 'panamaX_opt.png',
		videoId: 'upJmacEjONk',
		enableComments: true
	},
	{
		id: 18,
		title: 'Colombia',
		date: 'January 24, 2020 - February 5, 2020',
		imgName: 'colombia_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'colombia.md',
		summaryText: 'Soaked in the sunshine, colorful murals, family & friends',
		expenseImage: 'colombiaX_opt.png',
		videoId: 'XW8JcYTvaKI',
		enableComments: true
	},
	{
		id: 19,
		title: 'Peru',
		date: 'Feburary 5, 2020 - February 18, 2020',
		imgName: 'peru_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'peru.md',
		summaryText: 'Trudged through the rains to Machu Picchu and beyond',
		expenseImage: 'peruX_opt.png',
		videoId: 'XW8JcYTvaKI',
		enableComments: true
	},
	{
		id: 20,
		title: 'Bolivia',
		date: 'Feburary 18, 2020 - February 26, 2020',
		imgName: 'bolivia_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'bolivia.md',
		summaryText: 'Road tripped through Mars on Earth',
		expenseImage: 'boliviaX_opt.png',
		videoId: 'ICr3fDKDE6Q',
		enableComments: true
	},
	{
		id: 21,
		title: 'Chile & Patagonia',
		date: 'Feburary 26, 2020 - March 24, 2020',
		imgName: 'chile_opt.jpg',
		photoUrls: ['waterfall.jpg', 'waterfall.jpg'],
		textFile: 'chile.md',
		summaryText: 'Sandboarded and hiked through this mountainous country',
		expenseImage: 'chileX_opt.png',
		videoId: 'ICr3fDKDE6Q',
		enableComments: true
	}
	// {
	// 	id: 2,
	// 	title: 'Icelandic Roadtrip',
	// 	date: 'August 2017',
	// 	imgName: 'glassBeach.jpg',
	// 	photoUrls: ['glassBeach.jpg', 'glassBeach.jpg', 'glassBeach.jpg'],
	// 	textFile: 'iceland2017.txt',
	// 	summaryText: 'Drove around the entire country chasing waterfalls, volcanos, and fjords',
	// 	videoId: 'NLto1p8z614'
	// },
	// {
	// 	id: 3,
	// 	title: 'New Zealand',
	// 	date: 'November 2016',
	// 	imgName: 'MilfordSound.jpg',
	// 	photoUrls: ['MilfordSound.jpg', 'nz2.jpg', 'glassBeach.jpg'],
	// 	textFile: 'iceland2017.txt',
	// 	summaryText: 'A kiwi roadtrip with a friend named Ashwin',
	// 	videoId: '1UrqsHhnRT8'
	// },

	// {
	// 	id: 5,
	// 	title: 'Japan',
	// 	date: 'November 2016',
	// 	imgName: 'MtFuji.jpg',
	// 	photoUrls: ['MilfordSound.jpg', 'nz2.jpg', 'glassBeach.jpg'],
	// 	textFile: 'iceland2017.txt',
	// 	summaryText: 'Indulged in many cultural experiences',
	// 	videoId: 'Dr6ebJRngaQ'
	// },
	// {
	// 	id: 6,
	// 	title: 'Vail',
	// 	date: 'July 2015',
	// 	imgName: 'Vail.JPG',
	// 	photoUrls: ['glassBeach.jpg', 'lostCoast.jpg', 'glassBeach.jpg'],
	// 	textFile: 'iceland2017.txt',
	// 	summaryText: 'Skiied acres of fresh powda.',
	// },


	// {
	// 	id: 9,
	// 	title: 'Havasupai',
	// 	date: 'June 2017',
	// 	imgName: 'HavasuBackpacking.jpg',
	// 	photoUrls: ['HavasuBackpacking.jpg', 'lostCoast.jpg', 'glassBeach.jpg'],
	// 	textFile: 'havasupai2017.txt',
	// 	summaryText: 'Backpacked into paradise',
	// 	videoId: null
	// },
];

export default tripData;
